- name: Install dependencies
  apt:
    name: 
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - jq
      - fuse-overlayfs # required for docker on LXC
    state: present
    update_cache: true

- name: add GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker repository to apt
  apt_repository:
    filename: docker 
    #repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bullseye stable
    repo: deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable
    state: present

- name: Install docker engine
  apt:
    name: 
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    state: present
    update_cache: true

- name: Configure docker daemon
  copy:
    src: docker_daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify: restart docker
  tags: docker_daemon

- name: Install docker-compose
  import_tasks: compose.yml
  tags: docker_compose

- name: Install packages required for ansible to interact w/ python daemon on host
  apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: false
    
- name: Install required python packages
  pip:
    name:
      - docker
      - docker-compose
    state: present
